version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ControlDeDatos
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!
      MYSQL_DATABASE: ControlDeDatos
      MYSQL_USER: appuser
      MYSQL_PASSWORD: AppPass123!
    ports:
      - "3727:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ControlDeDatos-net

volumes:
  db_data:

networks:
  ControlDeDatos-net:
